CREATE TABLE PAIS (ID NUMBER PRIMARY KEY, 
                    nome varchar (30));
                    
CREATE TABLE ESTADO (ID_ESTADO NUMBER PRIMARY KEY,
                    NOME VARCHAR2(30),
                    IS_PAIS NUMBER) ;
                    
ALTER TABLE ESTADO ADD CONSTRAINT FK_ESTADO 
FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID_PAIS);

CREATE TABLE CIDADE (ID_CIDADE NUMBER,
                    NOME VARCHAR2(30),
                    ID_ESTADO NUMBER);

                    
ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE
FOREIGN KEY (ID_ESTADO) REFERENCES PAIS (ID_ESTADO);

CREATE TABLE BAIRRO (ID_BAIRRO NUMBER,
                        NOME VARCHAR2(30),
                        ID_CIDADE NUMBER);

ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO
FOREIGN KEY (ID_CIDADE) REFERENCES PAIS (ID_CIDADE);         

CREATE TABLE ENDERECO_CLIENTE (ID_CLIENTE NUMBER,
                                NOME VARCHAR2(100),
                                CEP VARCHAR2(12),
                                ID_BAIRRO NUMBER);
                            
ALTER TABLE ENDERECO_CLIENTE ADD CONSTRAINT FK_END_BAIRRO
FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO (ID_);                                   


